### ISSUE TITLE
[error] Tds.Protocol (#PID<0.3173.0>) failed to connect: ** (Tds.Error) tcp connect: timeout

### ISSUE THREAD

**Issue by ericlathrop** [livehelpnow/tds#102]
This error started spamming my console about once every 10 seconds:

`[error] Tds.Protocol (#PID<0.3173.0>) failed to connect: ** (Tds.Error) tcp connect: timeout`

I'm recently updated from `tds` 2.0.0 -> 2.0.4 and `db_connection` 2.0.6 -> 2.2.1, but even after switching back to the old versions, the log message remains.

The database connection seems to be working fine, so I'm not sure what's timing out.

Also, there's no stack trace, so it's really hard to track this down.

**Comment by mjaric** [comment]
Hi @ericlathrop does logged error occur while app is idle? 

I experience similar behavior with pre v2.0 on my laptop. When it goes to sleep while app is running, and then it goes back on, app flood console with same error since connection is lost, but it gets recovered after few moments. In my case it is normal behavior since connection was lost due power saving and connection was lost, but due the "nap" connection state was not changed. At least otp process was unaware of connection state change .

BTW, regarding the error you are seeing and what line it is, it is logged by DbConnection after [Tds.Protocol.connect](https://github.com/livehelpnow/tds/blob/50af9d0df124bd7292655bb153d9dd345d827077/lib/tds/protocol.ex#L415) fail to connect due timeout

**Comment by ericlathrop** [comment]
The message is printed whether or not the app is busy or idle. On my laptop it seems like it's about once every 20 seconds. It's making it hard to locate more important error messages in my server logs.

**Comment by mjaric** [comment]
I wrote small app that executes some query every random number of seconds and left it to run  couple of hours. Unfortunately I could not reproduce the issue. Test was conducted between two bare metal machines on same wired local network and both (app and mssql) have Windows 10 installed. Power Management is set to High Power Profile.

I can only assume that there is something with your network or power management causes this. There are couple of things you can do to diagnose your setup:

- Check what is packet loss between two machines that communicate by running couple times ping with arbitrary TCP segment sizes below MTU set on your card.
- You could also try sending wider package in ping and see if there is any loss
- Try other client from other platforms, but have in mind that some, for instance .NET could terminate connection each time query is executed if you are not explicit that you want to keep connection
- Try to use other computers combined (SQL + NEW,  then APP + NEW wit sql), maybe your network is buggy, I saw many times network cards "working" but with glitches similar to this. 
- Check if replacing router helps or use [crossover ](https://www.computercablestore.com/what-are-ethernet-crossover-cables)network cable between two computers
- If you are using WiFi and power management is set to save power then this could be the cause. For instance, this is default in case of Ubuntu os.

Each check should be done on both computers since only one is enough to cause the issue.

**Comment by ericlathrop** [comment]
I'm getting this error both in production (on AWS ECS) and on my laptop in Docker. On my laptop there shouldn't be any networking or power management issues.

**Comment by mjaric** [comment]
is it not too much if I ask minimal example that suffers from this issue? If possible with docker compose so I can be sure that I can reproduce the issue in my environment.

**Comment by mjaric** [comment]
I'll close this issue due lack of details and inactivity. If it is required, we can reopen it but I need sample project that can reproduce this issue
