### ISSUE TITLE
Cannot connect to Azure SQL Server instance

### ISSUE THREAD

**Issue by onkel-dirtus** [livehelpnow/tds#11]
I'm an utter MSSQL noob, but I think an encrypted connection is required to connect to sql server instances running on azure. I can use the pymssql python library to connect, so I don't think the issue is network related.

**Comment by danturn** [comment]
yeah, that's correct. Tds does an unencrypted login handshake and Azure won't support that

**Comment by bslobodin** [comment]
@danturn is this being worked on, by any chance?

**Comment by danturn** [comment]
@bslobodin I don't know I'm afraid, certainly not by me :)

**Comment by danturn** [comment]
Hi guys, 

You can actually use this with azure, if you put your username as username@servername to connect

this does create an unencrypted login to azure, but does seem to work

I believe this uses the pre tds 7.1 style login handshake (which freetds does too i think?) where there is no prelogin packet send and just immediately sends an unencrypted login 7 packet. 

just to make you aware this does mean that you're sending your username and password in clear text over the network (the password is sort of encrypted but is easily reversed, you can find out how online if you're interested) rather than ssl encrypted as it would be with a normal sql login

@bslobodin, @onkel-dirtus - hope that helps?

**Comment by danturn** [comment]
in addition (in case it helps anyone else) if you run the tds client on an azure vm they do a clever redirection thing (they send an envchange token in the login response which is supposed to cause the client to reconnect to a new server). this isnt supported in tds so you have 2 options. either change the code to connect as tds7.3 (its only in one place) or change the server setting via the azure rest api https://msdn.microsoft.com/en-us/library/azure/mt604439.aspx if the tds client is not running on an azure machine you probably wont have this issue though

**Comment by bottlenecked** [comment]
Hi all, I've submitted a pull request to fix this issue without downgrading to 7.3 [here](https://github.com/livehelpnow/tds/pull/61)

**Comment by mjaric** [comment]
released in v1.0.15
