### ISSUE TITLE
Federated Auth

### ISSUE THREAD

**Issue by matreyes** [livehelpnow/tds#122]
Hi,

The FEDAUTH stream allows to include a token to the Login7 message generated by an authentication provider (in my case I need to connect with ActiveDirectoryPassword authentication, which is used in AzureSQL).

It is independent of the NTLM protocol, but as @mjaric is working on that, I’m not sure if it will have conflicts if developed in parallel.

**Comment by matreyes** [comment]
Hi @mjaric .
A colleague is working in this feature, but SSL is required. Do you think your SSL branch is ready? 
Would yo be able to help us giving some guidelines?
Best.

**Comment by mjaric** [comment]
Hi @matreyes. In nutshell SSL workaround is implemented in PR #120 but I don't have environment to play with it or test it. You should know that TLS implementation is not quite done by the book, because initial message exchange for TLS handshake in TDS is not done in the same way as it is done with HTTP, and there was no "right" way how to extend erlangs ssl module. So this may be a problem in future if erlang ssl change internally.

Btw, I'm not working on any elixir/erlang project at the moment so I'm not sure if I can dedicate more hours on this code base until new elixir project appear that requirers mssql as db engine.

**Comment by matreyes** [comment]
Hi @mjaric. 

That is a big loss for our community. But thanks for this amazing work.

Best
