### ISSUE TITLE
ATTN packets

### ISSUE THREAD

**Issue by graves** [livehelpnow/tds#30]
When or under what conditions are they to be sent?

**Comment by danturn** [comment]
its not very well defined. certainly you can get them from the server if you send data in a format its not expecting. you also see them from tds clients if the time out is exceeded as its a way for a client to cancel a long running query on the server.

Generally if the SQL server is sending you one you've sent it something it doesnt understand or is not expecting. (obviously it provides no details about what that may be :) )

**Comment by mjaric** [comment]
It can be received if you try to cancel explicitly previous statement, comparing to other messages you could send, ATTN can be send during RPC/Batch execution and won't be queued. I think this is not yet handled correctly in TDS, since the rest of the messages need to be flushed (received by the client). TBD
