### ISSUE TITLE
Why do you stop using sp_executeSQL?

### ISSUE THREAD

**Issue by nerus** [livehelpnow/tds#58]
Why do you stop using sp_executeSQL?, In my past experience with sp_prepare, doing this in separate steps typically increases the total time involved because you are forcing more network round-trips to the statement execution: 1) for the prepare, 1 for the statement, and 1 for the unprepared. While I am no expert, it is my opinion that with using sp_executeSQL, the other two steps are not needed here and is more faster.

**Comment by mjaric** [comment]
It is much secured than allowing someone to give you statement with embedded values, which may inject some SQL developer didn't want. Second, I am not sure if prepare is slower than sp_executesql. Initially it is, on first execute of specific query, but you can reuse handle and send different values for parameters, so it will save SQL server to constantly recompile same query again and again. This make sense since you are building api who will have same script (query) but parameter values will change in each call (disclaimer: currently tds does not cache handles so it will be slower than sp_executesql). Third reason is that Ecto is working in such way, it asks for prepare statement, and then calls handle execute, so we had to follow that path.

Now, since ecto is not the only way and it is rather an ORM, I have some plans to cover some other things in TDS, things like SP exec, TVP, cursors..., but I can't promise when this will be done.

**Comment by nerus** [comment]
Thanks for your answer, I like the work that you are doing. I observed that you are doing a `SELECT 'pong' as [msg]`, i suggest change to  `SELECT getdate() as [datetime]`, and store the result it in somewhere like server_datetime to acces from anywhere, something like `Tds.SQLServerDateTime`

**Comment by nerus** [comment]
Thanks for your answer, I like the work that you are doing. I observed that you are doing a `SELECT 'pong' as [msg]`, i suggest change to  `SELECT getdate() as [datetime]`, and store the result it in somewhere like server_datetime to acces from anywhere, something like `Tds.SQLServerDateTime`

**Comment by mjaric** [comment]
Sure, do you have some concrete use case?

**Comment by naag** [comment]
We're sometimes also running into performance issues due to `sp_prepare` because it only cares about density estimates for it's query plan (see https://www.brentozar.com/archive/2018/03/sp_prepare-isnt-good-sp_executesql-performance/). Do you think there is any way to trick Ecto into using a different workflow? Or maybe having a configuration option like JDBC does for the execution mode?

**Comment by mjaric** [comment]
I doubt that any of two is a silver bullet. Anyhow, we could make a switch in configuration, as you suggested. When `DbConnection.handle_prepare/3` is about to be executed, there is already attached prepared sql statement as string into `%Tds.Query{}` struct, in `statement` attribute. Then, same struct is passed to `DbConnection.handle_execute/4`. We can simply ignore sp_prepare call in handle_prepare and then in handle_execute use `sp_executesql` instead when such preference is set in configuration. I would like to keep prepare as default if none preference is set in configuration.

**Comment by naag** [comment]
That sounds reasonable :-) Would you mind if I try to go ahead with a pull request?

**Comment by mjaric** [comment]
Actually I appreciate! Thanx!
