### ISSUE TITLE
Is money supposed to be a decimal?

### ISSUE THREAD

**Issue by rzane** [livehelpnow/tds#60]
When the value comes out of the database, it's a float. Would this value be better represented as a decimal?

The ruby library [`tiny_tds`](https://github.com/rails-sqlserver/tiny_tds) seems to treat this value as a decimal.

**Comment by mjaric** [comment]
In erlang runtime you shouldn't worry as long as value do not leave erlang runtime, it will keep precision even when you do computation. As I can see from code in master, decoding is done, and probably works ok, but encoding is missing and it will probably use float instead, which could give you some inaccurate results because it does not use round function when it "loses erlang precision" instead it is converted into IEEE 754 little endian binary representation. The lost in precision could be too high for values which represents money.  I'm not sure when we will support `:money` at the moment.

**Comment by wanton7** [comment]
I don't think it's wise to convert money to a decimal. money and smallmoney are fixed point data types. money is 64 bit integer and smallmoney is 32 bit integer. Decimal place is just shown at four decimals. I don't know how decimal type works internally but I bet it's not designed to handle money. You might get some rounding errors and you REALLY don't want rounding errors when handling money. I would use integer multiplied by 10000 instead, so that 0.9999 would return integer 9999 and if you wanted to send 1.9999 you would use 19999.

Example https://docs.microsoft.com/en-us/sql/t-sql/data-types/money-and-smallmoney-transact-sql?view=sql-server-2017 smallmoney range -214,748.3648 to 214,748.3647 and 32 bit integer range is −2147483648 to 2147483647.

**Comment by rzane** [comment]
@wanton7 I think you're actually making a case *for* using decimal rather than float.

> money and smallmoney are fixed point data types. {...} You might get some rounding errors and you REALLY don't want rounding errors when handling money.

The decimal datatype is fixed point, which is why I'm suggesting that it should be used instead of float. Here's a really simple example of the problem with using floats:

```elixir
iex(3)> 0.1 * 3
0.30000000000000004

iex(2)> Decimal.new("0.1") |> Decimal.mult(3)
#Decimal<0.3>
```

>  I would use integer multiplied by 10000 instead, so that 0.9999 would return integer 9999 and if you wanted to send 1.9999 you would use 19999.

While I don't disagree with you on this point, I don't think that's relevant in this discussion. For better or worse, people need to read from databases that *already* contain values stored using the money datatype.

**Comment by wanton7** [comment]
@rzane I meant that if someone has money datatype in their database that column would be converted to an integer multiplied 10000 by driver and integer would converted to money divided by 10000 when needed without losing any decimals.

Like I said I don't know how decimal internals work but there are lot of fixed point implementations and lot of them are not 10 based because it's faster to use bitshift. So you could lose precision if decimal is using bitshift internally.

**Comment by mjaric** [comment]
@wanton7 internally money is split into two 4 bytes integer, each represents more and less significat parts. 

Currently it is decoded like this

```elixir
<<money::signed-64>> = <<money_m::32, money_l::32>>
    Float.round(money * 0.0001, 4)
```

So it won't lose any precision even tho it will be float in your app. What so ever, if you do any arithmetic operations in memory it will be precise. 

Encoding. When you need to store it in database, best option would be to use decimal parameter type, since the case @rzane mentioned above. Float is not good since it is transferred over wire as approximation (ieee-754 format).

I'm not sure at the moment what tds_ecto does with ecto :money type, but it is probably converted into Decimal. Disclaimer, I didn't wrote all code so don't take me for granted  :)
